version: '2'
services:
  influxdb:
    image: influxdb:1.7
    ports:
      - '8086:8086'
      - '38086:38086'
    volumes:
      - ./influxdb/lib/:/var/lib/influxdb

      
    environment:
      - INFLUXDB_DB=jmeterProject
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  
  grafana:
    image: grafana/grafana:6.5.0
    ports:
      - '3000:3000'
    volumes:
    - grafana_data:/var/lib/grafana
    
    depends_on:
      - influxdb
    links:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      
volumes:
  grafana_data:
  influxdb-storage:
    external: true
